version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=qgenie
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_PORT=5432
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=qgenie
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 